
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ERICA
 */
public class MainGui extends javax.swing.JFrame {
   

    /**
     * Creates new form MainGui
     */
    public MainGui(Machine machine) {
    this.machine = machine;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        purchaseOption = new javax.swing.JButton();
        maintenanceOption = new javax.swing.JButton();
        exitOption = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Regular Vending Machine");

        purchaseOption.setText("Make a Purchase");
        purchaseOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOptionActionPerformed(evt);
            }
        });

        maintenanceOption.setText("Open Maintenance");
        maintenanceOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceOptionActionPerformed(evt);
            }
        });

        exitOption.setText("Exit Vending Machine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(exitOption)
                    .addComponent(maintenanceOption)
                    .addComponent(purchaseOption)
                    .addComponent(jLabel1))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(purchaseOption)
                .addGap(18, 18, 18)
                .addComponent(maintenanceOption)
                .addGap(18, 18, 18)
                .addComponent(exitOption)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main Menu", jPanel1);

        jPanel4.setLayout(new java.awt.GridLayout(8, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vending Machine", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(" Maintenance", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maintenanceOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceOptionActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_maintenanceOptionActionPerformed

    private void purchaseOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseOptionActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        getUserPayment();
        generateProductButtons();
    }//GEN-LAST:event_purchaseOptionActionPerformed

    private void getUserPayment() {
        String input = JOptionPane.showInputDialog(this, "Enter the payment in quantities using the format [200-100-50-20-10-5-1]:");
     ArrayList<Currency> paymentDenominations = machine.extractPayment(input);

                // INPUT STORED IN CURRENCY QUANTITIES
                machine.updateCurrencyStockWithPayment(paymentDenominations);
                // INPUT VALIDATION -> INT VALUE
                int totalPayment = machine.calculateTotalPayment(paymentDenominations);
                jOptionPane1.setMessage("Total Payment is " + totalPayment);
                jOptionPane1.createDialog(this, "Payment").setVisible(true);
                
              
    }
    
    private void generateProductButtons() {
    ArrayList<Slot> slotList = machine.getSlotList();
    ButtonGroup buttonGroup = new ButtonGroup();  // Create a ButtonGroup to group the radio buttons

    // Clear any existing buttons in the panel
    jPanel4.removeAll();

    for (Slot slot : slotList) {
        JRadioButton radioButton = new JRadioButton(slot.getProduct().getName());
        buttonGroup.add(radioButton);  // Add the radio button to the ButtonGroup
        JLabel stockLabel = new JLabel("Stock: " + slot.getStock());
        JLabel priceLabel = new JLabel("Price: PHP " + slot.getProduct().getPrice());
        JLabel caloriesLabel = new JLabel("Calories: " + slot.getProduct().getCalories());
        
        
        jPanel4.add(radioButton);  // Add the radio button to the panel
      jPanel4.add(stockLabel);
        jPanel4.add(priceLabel);
        jPanel4.add(caloriesLabel); 
    }

    jPanel4.revalidate();  // Revalidate the panel to update the layout
    jPanel4.repaint();  // Repaint the panel to reflect the changes
    jPanel4.setVisible(true);
}


    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Machine machine = new Machine();
        machine.initializeCurrencies();

        // #1 Intialize Products
        Product apple = new Product("Apple", 10, 50);
        Product banana = new Product("Banana", 8, 80);
        Product orange = new Product("Orange", 12, 60);
        Product strawberry = new Product("Strawberry", 15, 40);
        Product pineapple = new Product("Pineapple", 20, 70);
        Product watermelon = new Product("Watermelon", 18, 30);
        Product mango = new Product("Mango", 25, 90);
        Product kiwi = new Product("Kiwi", 13, 55);

        // #2 Assign Products to Slot
        machine.addProduct(apple, 5);
        machine.addProduct(banana, 3);
        machine.addProduct(orange, 4);
        machine.addProduct(strawberry, 2);
        machine.addProduct(pineapple, 6);
        machine.addProduct(watermelon, 1);
        machine.addProduct(mango, 3);
        machine.addProduct(kiwi, 4);
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
    @Override
    public void run() {
        new MainGui(machine).setVisible(true);
    }
        });
    }
    private String userInput;
    private Machine machine;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton maintenanceOption;
    private javax.swing.JButton purchaseOption;
    // End of variables declaration//GEN-END:variables
}
