
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ERICA
 */
public class MainGui extends javax.swing.JFrame {
   

    /**
     * Creates new form MainGui
     */
    public MainGui(Machine machine) {
    this.machine = machine;
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        purchaseOption = new javax.swing.JButton();
        maintenanceOption = new javax.swing.JButton();
        exitOption = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        confirmPurchaseButton = new javax.swing.JButton();
        transactionCancelButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        anotherPurchaseButton = new javax.swing.JButton();
        cancelTransactionButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Regular Vending Machine");

        purchaseOption.setText("Make a Purchase");
        purchaseOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseOptionActionPerformed(evt);
            }
        });

        maintenanceOption.setText("Open Maintenance");
        maintenanceOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceOptionActionPerformed(evt);
            }
        });

        exitOption.setText("Exit Vending Machine");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(exitOption)
                    .addComponent(maintenanceOption)
                    .addComponent(purchaseOption)
                    .addComponent(jLabel1))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(purchaseOption)
                .addGap(18, 18, 18)
                .addComponent(maintenanceOption)
                .addGap(18, 18, 18)
                .addComponent(exitOption)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main Menu", jPanel1);

        jPanel4.setLayout(new java.awt.GridLayout(8, 2));

        confirmPurchaseButton.setText("Confirm Purchase");
        confirmPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPurchaseButtonActionPerformed(evt);
            }
        });

        transactionCancelButton.setText("Cancel Transaction");
        transactionCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(confirmPurchaseButton)
                .addGap(47, 47, 47)
                .addComponent(transactionCancelButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPurchaseButton)
                    .addComponent(transactionCancelButton)))
        );

        anotherPurchaseButton.setText("Make Another Purchase");
        anotherPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anotherPurchaseButtonActionPerformed(evt);
            }
        });

        cancelTransactionButton1.setText("Dispense Change");
        cancelTransactionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTransactionButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anotherPurchaseButton)
                .addGap(40, 40, 40)
                .addComponent(cancelTransactionButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anotherPurchaseButton)
                    .addComponent(cancelTransactionButton1)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vending Machine", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(" Maintenance", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>                        

    private void maintenanceOptionActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        jTabbedPane1.setSelectedIndex(2);
        
    }                                                 

    private void purchaseOptionActionPerformed(java.awt.event.ActionEvent evt) {                                               
        jTabbedPane1.setSelectedIndex(1);
        jPanel6.setVisible(false);
        generateProductButtons();
        getUserPayment();
        
    }                                              

    private void confirmPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
       String selectedProduct = buttonGroup.getSelection().getActionCommand();
    JOptionPane.showMessageDialog(this, "Selected Product: " + selectedProduct);
    int totalPayment = userPayment;

    performPurchase(selectedProduct, totalPayment);
    }                                                     

    private void transactionCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        machine.updateCurrencyStockWithChange(machine.calculateChangeQuantity(userPayment));
        jTabbedPane1.setSelectedIndex(0);
    }                                                       

    private void anotherPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        String selectedProduct = buttonGroup.getSelection().getActionCommand();
    JOptionPane.showMessageDialog(this, "Selected Product: " + selectedProduct);
    int totalPayment = change;

    performPurchase(selectedProduct, totalPayment);
    }                                                     

    private void cancelTransactionButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    
    private void getUserPayment() {
        String input = JOptionPane.showInputDialog(this, "Enter the payment in quantities using the format [200-100-50-20-10-5-1]:");
     ArrayList<Currency> paymentDenominations = machine.extractPayment(input);

                // INPUT STORED IN CURRENCY QUANTITIES
                machine.updateCurrencyStockWithPayment(paymentDenominations);
                // INPUT VALIDATION -> INT VALUE
                userPayment = machine.calculateTotalPayment(paymentDenominations);
                jOptionPane1.setMessage("Total Payment is " + userPayment);
                jOptionPane1.createDialog(this, "Payment").setVisible(true);       
               
    }
    
    private void performPurchase(String selectedProduct, int totalPayment) {
    int slotIndex = -1;

    for (int i = 0; i < machine.getSlotList().size(); i++) {
        Slot slot = machine.getSlotList().get(i);
        if (slot.getProduct().getName().equals(selectedProduct)) {
            slotIndex = i;
        }
    }

    if (machine.isValidSlotAndPayment(slotIndex, totalPayment)) {
        int productPrice = machine.getSlot(slotIndex).getProduct().getPrice();
         change = machine.calculateTotalChange(productPrice, totalPayment);

        // VALIDATION -> CALCULATE IF CURRENCY STOCK IS SUFFICIENT FOR CHANGE
        if (machine.stockHasSufficientChange(change)) {
            machine.generateTransaction(totalPayment, machine.getSlot(slotIndex).getProduct(), change);
            // DISPENSE PRODUCT (UPDATES SLOT STOCK ETC.)
            machine.updateStock(slotIndex);
            String product = machine.getSlot(slotIndex).getProduct().getName();

            jOptionPane2.setMessage("Dispensed: " + selectedProduct + "\n"+ "Change: " + change);
            jOptionPane2.createDialog(this, "Product").setVisible(true);
            
            generateProductButtons();
            jPanel5.setVisible(false);
            jPanel6.setVisible(true);
        }
    }
}
    
    private void generateProductButtons() {
    ArrayList<Slot> slotList = machine.getSlotList();
    buttonGroup = new ButtonGroup();  // Create a ButtonGroup to group the radio buttons

    // Clear any existing buttons in the panel
    jPanel4.removeAll();

    for (Slot slot : slotList) {
        JRadioButton radioButton = new JRadioButton(slot.getProduct().getName());
        
        radioButton.setActionCommand(slot.getProduct().getName());
        buttonGroup.add(radioButton);  // Add the radio button to the ButtonGroup
        JLabel stockLabel = new JLabel("Stock: " + slot.getStock());
        JLabel priceLabel = new JLabel("Price: PHP " + slot.getProduct().getPrice());
        JLabel caloriesLabel = new JLabel("Calories: " + slot.getProduct().getCalories());
        
        
        jPanel4.add(radioButton);  // Add the radio button to the panel
        jPanel4.add(stockLabel);
        jPanel4.add(priceLabel);
        jPanel4.add(caloriesLabel); 
    }

    jPanel4.revalidate();  // Revalidate the panel to update the layout
    jPanel4.repaint();  // Repaint the panel to reflect the changes
    jPanel4.setVisible(true);
}

    




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Machine machine = new Machine();
        machine.initializeCurrencies();

        // #1 Intialize Products
        Product apple = new Product("Apple", 10, 50);
        Product banana = new Product("Banana", 8, 80);
        Product orange = new Product("Orange", 12, 60);
        Product strawberry = new Product("Strawberry", 15, 40);
        Product pineapple = new Product("Pineapple", 20, 70);
        Product watermelon = new Product("Watermelon", 18, 30);
        Product mango = new Product("Mango", 25, 90);
        Product kiwi = new Product("Kiwi", 13, 55);

        // #2 Assign Products to Slot
        machine.addProduct(apple, 5);
        machine.addProduct(banana, 3);
        machine.addProduct(orange, 4);
        machine.addProduct(strawberry, 2);
        machine.addProduct(pineapple, 6);
        machine.addProduct(watermelon, 1);
        machine.addProduct(mango, 3);
        machine.addProduct(kiwi, 4);
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
    @Override
    public void run() {
        new MainGui(machine).setVisible(true);
    }
        });
    }
    private String userInput;
    private Machine machine;
    private ButtonGroup buttonGroup; 
    private int userPayment;
    private int change;

    // Variables declaration - do not modify                     
    private javax.swing.JButton anotherPurchaseButton;
    private javax.swing.JButton cancelTransactionButton1;
    private javax.swing.JButton confirmPurchaseButton;
    private javax.swing.JButton exitOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton maintenanceOption;
    private javax.swing.JButton purchaseOption;
    private javax.swing.JButton transactionCancelButton;
    // End of variables declaration                   
}
