/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject9;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author ERICA
 */
public class SVMPanel extends javax.swing.JPanel {
    private Machine machine;
    private int totalPayment;
    private int change;
    private ComboProductsPanel comboProductsPanel;
    /**
     * Creates new form MainMenuJPanel
     */

    
    public SVMPanel(Machine machine, int totalPayment) {
        this.machine = machine;
        this.totalPayment = totalPayment;
        initComponents();
        initializeComboProductsPanel(machine); // Call the method to initialize ProductsPanel with the existing Machine
        svmChangeButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        svmChangeButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        svmPurchaseButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(482, 470));

        titleLabel.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel.setText("FROYO VENDING MACHINE");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        svmChangeButton.setBackground(new java.awt.Color(209, 235, 209));
        svmChangeButton.setFont(new java.awt.Font("Agency FB", 1, 21)); // NOI18N
        svmChangeButton.setForeground(new java.awt.Color(255, 255, 255));
        svmChangeButton.setText("Dispense Change");
        svmChangeButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        svmChangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmChangeButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        svmPurchaseButton.setBackground(new java.awt.Color(209, 235, 209));
        svmPurchaseButton.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        svmPurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        svmPurchaseButton.setText("Purchase");
        svmPurchaseButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        svmPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svmPurchaseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(svmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(svmPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(svmPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(svmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void svmChangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svmChangeButtonActionPerformed
       String changeString = machine.dispenseChange(change);

        machine.updateCurrencyStockWithChange(machine.calculateChangeQuantity(change));
               
        JOptionPane.showMessageDialog(this, "Change is " + changeString + "\n" + " = PHP"+ change);
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
       javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "MainMenuPanel");

    }//GEN-LAST:event_svmChangeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        machine.updateCurrencyStockWithChange(machine.calculateChangeQuantity(totalPayment));
        JOptionPane.showMessageDialog(this, "Payment returned: PHP "+ totalPayment);
        
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
       javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "MainMenuPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void svmPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svmPurchaseButtonActionPerformed
                                              
    ComboProductsPanel comboProductsPanel = (ComboProductsPanel) jPanel1.getComponent(0);
    HashMap<Product, Integer> selectedComboProducts = comboProductsPanel.getSelectedComboProducts();

    if (machine.hasProducts(selectedComboProducts)) {
        ArrayList<Product> comboArray = createComboArray(selectedComboProducts);

        Combo combo = new Combo(comboArray);
        performPurchase(combo, totalPayment);
        totalPayment = change;
        jButton1.setVisible(false);
    } else {

        JOptionPane.showMessageDialog(this, "Please select a product before making a purchase.");
    }
        
    }//GEN-LAST:event_svmPurchaseButtonActionPerformed

        private void initializeComboProductsPanel(Machine machine) {
    if (comboProductsPanel != null) {
        jPanel1.remove(comboProductsPanel);
    }
    
    comboProductsPanel = new ComboProductsPanel(machine);
    
    jPanel1.add(comboProductsPanel, BorderLayout.CENTER);
    
    jPanel1.revalidate();
    jPanel1.repaint();
    }
        
    private ArrayList<Product> createComboArray(HashMap<Product, Integer> selectedComboProducts) {
    ArrayList<Product> comboArray = new ArrayList<>();

    for (Map.Entry<Product, Integer> entry : selectedComboProducts.entrySet()) {
        Product selectedProduct = entry.getKey();
        int count = entry.getValue();

        for (int i = 0; i < count; i++) {
            comboArray.add(selectedProduct);
        }
    }

    return comboArray;
}
        
        private void performPurchase(Combo comboItems, int totalPayment){
       int comboPrice = comboItems.getPrice();
       change = machine.calculateTotalChange(comboPrice, totalPayment);
    
        if (machine.isValidPayment(comboPrice, totalPayment)) {

            // VALIDATION -> CALCULATE IF CURRENCY STOCK IS SUFFICIENT FOR CHANGE
            if (machine.stockHasSufficientChange(change)) {
                machine.generateTransaction(totalPayment, comboItems, change);
                // DISPENSE PRODUCT (UPDATES SLOT STOCK ETC.)
                machine.updateComboStock(comboItems);
  
                initializeComboProductsPanel(machine);
               
                String message = "Dispensed: " + comboItems.initializeComboName() + "\n" + "Change: " + change;
                JOptionPane.showMessageDialog(this, message);
                
                svmChangeButton.setVisible(true);                
            }
        }  
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton svmChangeButton;
    private javax.swing.JButton svmPurchaseButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
