public class Transaction {
    private int payment;
    private Product product;
    private int change; 
    //Auto generated by Machine 
    public Transaction(int payment, Product product, int change) {
        this.payment = payment;
        this.product = product;
        this.change = change;
    }

    public int getPayment() {
        return payment;
    }

    public Product getProduct() {
        return product;
    }

    public int getChange() {
        return change;
    }

}
