/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject9;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author ERICA
 */
public class TransactionPanel extends javax.swing.JPanel {
    private Machine machine;
    private int totalPayment;
    /**
     * Creates new form MainMenuJPanel
     */
    public TransactionPanel(Machine machine, int totalPayment) {
        this.machine = machine;
        this.totalPayment = totalPayment;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        comboFroyoButton = new javax.swing.JButton();
        soloButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        titleLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(482, 470));

        titleLabel.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 204));
        titleLabel.setText("FROYO VENDING MACHINE");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        comboFroyoButton.setBackground(new java.awt.Color(153, 204, 255));
        comboFroyoButton.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        comboFroyoButton.setForeground(new java.awt.Color(255, 255, 255));
        comboFroyoButton.setText("Create Your Own FroYo");
        comboFroyoButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        comboFroyoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFroyoButtonActionPerformed(evt);
            }
        });

        soloButton.setBackground(new java.awt.Color(209, 235, 209));
        soloButton.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        soloButton.setForeground(new java.awt.Color(255, 255, 255));
        soloButton.setText("Buy Ingredients");
        soloButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 5, true));
        soloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soloButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 153, 153));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        titleLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        titleLabel1.setForeground(new java.awt.Color(204, 204, 255));
        titleLabel1.setText("MAKE A TRANSACTION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(6, 6, 6))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboFroyoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(comboFroyoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(soloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void soloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soloButtonActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        RVMPanel rvmPanel = new RVMPanel(machine,totalPayment);

       javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
       jLayeredPane1.add(rvmPanel, "rvmPanel");
       
        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "rvmPanel");
    }//GEN-LAST:event_soloButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        machine.updateCurrencyStockWithChange(machine.calculateChangeQuantity(totalPayment));
        JOptionPane.showMessageDialog(this, "Payment returned: PHP "+ totalPayment);
        
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
       javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "MainMenuPanel");
      
    }//GEN-LAST:event_exitButtonActionPerformed

    private void comboFroyoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFroyoButtonActionPerformed
        mainJFrame frame = (mainJFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        
        SVMPanel svmPanel = new SVMPanel(machine,totalPayment);

       javax.swing.JLayeredPane jLayeredPane1 = frame.getjLayeredPane1();
       jLayeredPane1.add(svmPanel, "svmPanel");
       
        CardLayout cardLayout = (CardLayout) jLayeredPane1.getLayout();
        cardLayout.show(jLayeredPane1, "svmPanel");
    }//GEN-LAST:event_comboFroyoButtonActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comboFroyoButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton soloButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables
}
