import java.util.ArrayList;

public class Transaction {
    private int payment;
    private ArrayList<Product> products;
    private int change; 
    
    //Auto generated by Machine 
    public Transaction(int payment, Product product, int change) {
        this.payment = payment;
        this.products = intializeProduct(product);
        this.change = change;
    }
    //Auto generated by Special
    public Transaction(int payment, Combo combo, int change) {
        this.payment = payment;
        this.products = intializeCombo(combo);
        this.change = change;
    }

    //Create Arraylist with 1 product
    public ArrayList<Product> intializeProduct(Product product) {
        ArrayList<Product> products = new ArrayList<Product>();
        products.add(product);
        return products;
    }
    //Get ingredients of the combo
    public ArrayList<Product> intializeCombo(Combo combo) {
        ArrayList<Product> ingredients = new ArrayList<Product>();
        for (int i = 0; i < combo.getIngredients().size(); i++) {
            ingredients.add(combo.getIngredients().get(i));
        }
        return ingredients;
    }

    public ArrayList<Product> getProducts() {
        return products;
    }
    public int getChange() {
        return change;
    }
    public int getPayment() {
        return payment;
    }

}
